# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose


services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - PORT=9999
      # Database host, can be replaced with the IP of an existing database server
      - DB_HOST=db
      # Database port
      - DB_PORT=3306
      # Database name
      - DB_NAME=vines
      # Database user
      - DB_USERNAME=vines
      # Database password
      - DB_PASSWORD=vines
    volumes:
      - ./storage:/app/vines/storage
    ports:
      - 9999:9999
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: vines
      MYSQL_USER: vines
      MYSQL_PASSWORD: vines
      MYSQL_ROOT_PASSWORD: vines
    restart: always
    expose:
     - 3306
    volumes:
      - ./storage/db/mysql:/var/lib/mysql

